### ISSUE TITLE
./bootstrap error

### ISSUE THREAD

**Issue by tueboesen** [BrianPugh/python-template#19]
I was trying out this template today, but ran into the follow error:
I am running it on Ubuntu.

```
(base) tue@tue-ubuntu:~/PycharmProjects/Multi-body-pendulum$ ./bootstrap
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/tue/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.4.0): Done

Poetry (1.4.0) is installed now. Great!

You can test that everything is set up by executing:

`poetry --version`

Enter your name: Tue Jensen Boesen
Python Module Name: Multi-Body-Pendulum
"Multi-Body-Pendulum" is not a valid python identifier.
Python Module Name: MultiBody-Pendulum
"MultiBody-Pendulum" is not a valid python identifier.
Python Module Name: MultiBodyPendulum
"MultiBodyPendulum" should be all lower case.
Python Module Name: multibodypendulum
Is this going to be a library? [default: yes]: 
Are you going to add type hints? [default: yes]: 
Would you like to include a CLI using Typer? [default: yes]: 
Creating virtualenv multibodypendulum in /home/tue/PycharmProjects/Multi-body-pendulum/.venv
Updating dependencies
Resolving dependencies... (7.3s)

Package operations: 49 installs, 1 update, 0 removals

  • Installing certifi (2022.12.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing markupsafe (2.1.2)
  • Installing urllib3 (1.26.15)
  • Installing alabaster (0.7.13): Pending...
  • Installing attrs (22.2.0): Pending...
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing alabaster (0.7.13): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing alabaster (0.7.13): Downloading... 100%
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing alabaster (0.7.13): Installing...
  • Installing attrs (22.2.0): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 100%
  • Installing babel (2.12.1): Downloading... 0%
  • Installing attrs (22.2.0): Downloading... 100%
  • Installing babel (2.12.1): Downloading... 0%
  • Installing alabaster (0.7.13)
  • Installing attrs (22.2.0): Downloading... 100%
  • Installing babel (2.12.1): Downloading... 0%
  • Installing distlib (0.3.6): Downloading... 0%
  • Installing babel (2.12.1): Downloading... 0%
  • Installing distlib (0.3.6): Downloading... 0%
  • Installing attrs (22.2.0): Installing...
  • Installing babel (2.12.1): Downloading... 0%
  • Installing distlib (0.3.6): Downloading... 0%
  • Installing distlib (0.3.6): Downloading... 100%
  • Installing distlib (0.3.6): Installing...
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing babel (2.12.1): Downloading... 0%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing attrs (22.2.0)
  • Installing babel (2.12.1): Downloading... 0%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing babel (2.12.1): Downloading... 10%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing babel (2.12.1): Downloading... 40%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing babel (2.12.1): Downloading... 60%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing filelock (3.10.0): Pending...
  • Installing exceptiongroup (1.1.1): Downloading... 0%
  • Installing filelock (3.10.0): Pending...
  • Installing filelock (3.10.0): Downloading... 0%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Downloading... 0%
  • Installing filelock (3.10.0): Downloading... 0%
  • Installing babel (2.12.1): Downloading... 80%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Pending...
  • Installing exceptiongroup (1.1.1): Downloading... 0%
  • Installing filelock (3.10.0): Downloading... 0%
  • Installing filelock (3.10.0): Downloading... 100%
  • Installing filelock (3.10.0): Installing...
  • Installing filelock (3.10.0)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1): Downloading... 100%
  • Installing filelock (3.10.0)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1): Installing...
  • Installing filelock (3.10.0)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1): Downloading... 0%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Downloading... 0%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing babel (2.12.1): Downloading... 100%
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Downloading... 0%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Downloading... 0%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing babel (2.12.1): Installing...
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1): Downloading... 0%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1): Downloading... 10%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1): Downloading... 50%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1): Downloading... 100%
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1): Installing...
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing docutils (0.17.1)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing babel (2.12.1)
  • Installing distlib (0.3.6)
  • Installing docutils (0.17.1)
  • Installing exceptiongroup (1.1.1)
  • Installing filelock (3.10.0)
  • Installing imagesize (1.4.1)
  • Installing iniconfig (2.0.0)
  • Installing jinja2 (3.1.2)
  • Installing packaging (23.0)
  • Installing platformdirs (3.1.1)
  • Installing pluggy (1.0.0)
  • Installing pygments (2.14.0)
  • Installing requests (2.28.2)
  • Updating setuptools (67.4.0 -> 67.6.0)
  • Installing snowballstemmer (2.2.0)
  • Installing sphinxcontrib-applehelp (1.0.4)
  • Installing sphinxcontrib-devhelp (1.0.2)
  • Installing sphinxcontrib-htmlhelp (2.0.1)
  • Installing sphinxcontrib-jsmath (1.0.1)
  • Installing sphinxcontrib-qthelp (1.0.3)
  • Installing sphinxcontrib-serializinghtml (1.1.5)
  • Installing toml (0.10.2)
  • Installing tomli (2.0.1)
  • Installing cfgv (3.3.1)
  • Installing click (8.1.3)
  • Installing coverage (5.5)
  • Installing dunamai (1.16.0)
  • Installing identify (2.5.20)
  • Installing mypy-extensions (1.0.0)
  • Installing nodeenv (1.7.0)
  • Installing pathspec (0.11.1)
  • Installing pytest (7.2.2)
  • Installing pyyaml (6.0)
  • Installing sphinx (4.5.0)
  • Installing tomlkit (0.11.6)
  • Installing virtualenv (20.21.0)
  • Installing black (23.1.0)
  • Installing poetry-dynamic-versioning (0.16.0)
  • Installing pre-commit (2.21.0)
  • Installing pytest-cov (3.0.0)
  • Installing pytest-mock (3.10.0)
  • Installing sphinx-rtd-theme (1.0.0)
  • Installing typer (0.7.0)
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: multibodypendulum (0.0.0)
pre-commit installed at .git/hooks/pre-commit
[INFO] Initializing environment for https://github.com/charliermarsh/ruff-pre-commit.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/asottile/blacken-docs.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/fredrikaverpil/creosote.git.
[INFO] Initializing environment for https://github.com/codespell-project/codespell.
[INFO] Installing environment for https://github.com/charliermarsh/ruff-pre-commit.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/asottile/blacken-docs.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/fredrikaverpil/creosote.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/codespell-project/codespell.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
ruff.....................................................................Passed
black....................................................................Passed
blacken-docs.............................................................Passed
check for added large files..............................................Passed
check python ast.........................................................Passed
check builtin type constructor use.......................................Passed
check for case conflicts.................................................Passed
check docstring is first.................................................Passed
check that scripts with shebangs are executable..........................Passed
check for merge conflicts................................................Passed
check json...........................................(no files to check)Skipped
check toml...............................................................Passed
check xml................................................................Passed
check yaml...............................................................Passed
debug statements (python)................................................Passed
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing .idea/Multi-body-pendulum.iml
Fixing .idea/vcs.xml
Fixing .idea/inspectionProfiles/profiles_settings.xml
Fixing .idea/modules.xml
Fixing .idea/inspectionProfiles/Project_Default.xml

pretty format json...................................(no files to check)Skipped
fix requirements.txt.................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
creosote.................................................................Passed
codespell................................................................Passed
Traceback (most recent call last):
  File "/home/tue/PycharmProjects/Multi-body-pendulum/./bootstrap", line 253, in <module>
  File "/home/tue/PycharmProjects/Multi-body-pendulum/./bootstrap", line 244, in main
  File "/home/tue/PycharmProjects/Multi-body-pendulum/./bootstrap", line 54, in git
  File "/home/tue/mambaforge/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/tue/mambaforge/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'bootstrap from template']' returned non-zero exit status 1.

```

**Comment by BrianPugh** [comment]
This happened because I think you opened the project with pycharm prior to running `bootstrap`. One of the pre-commit hooks didn't like some of the formatting in one of the pycharm configuration files. Regardless, this shouldn't happen, so here are two things:

1. It failed at the last step, so for now, you can proceed just by running:
```
git add -u  # Adds the files fixed by pre-commit
git commit -m "bootstrap from template"
# now bootstrapping is fully complete
```
2. I'll update some stuff right now so this doesn't happen again in the future.
